BEGIN --reportText

    PRINT '    fill reportText'

    MERGE INTO [rep].[reportText] t
    USING
    (
        SELECT N'BeispielText' AS [text],N'{"de":"BeispielText","en":"SampleText"}' AS [translatedText]
        UNION ALL SELECT N'isActive',N'{"de":"aktiv","en":"activ"}'
        UNION ALL SELECT N'additionalExtraShift',N'{"de":"zuzgl. Sonderschicht","en":"additional Extrashift"}'
        UNION ALL SELECT N'axis',N'{"de":"Achse","en":"Axis"}'
        UNION ALL SELECT N'billNumber',N'{"de":"Beleg-Nr.","en":"BillNumber"}'
        UNION ALL SELECT N'building',N'{"de":"Gebäude","en":"Building"}'
        UNION ALL SELECT N'calculatedRegularOutputPerHour',N'{"de":"Richtleistung pro Stunde","en":"Calculated Regular Output"}'
        UNION ALL SELECT N'calendar',N'{"de":"Kalender","en":"Calendar"}'
        UNION ALL SELECT N'changeDate',N'{"de":"geändert am","en":"changed"}'
        UNION ALL SELECT N'company',N'{"de":"Gesellschaft","en":"Company"}'
        UNION ALL SELECT N'comment',N'{"de":"Bermerkung","en":"Comment"}'
        UNION ALL SELECT N'confirmationOfWork',N'{"de":"Auftragsbescheinigung","en":"Confirmation of Work"}'        
        UNION ALL SELECT N'confirmationOfWorkLabel1',N'{"de":"gemäß des gültigen Einheispreiskatalogs {{priceCatalogFrom}} erteilt.","en":"This work order is placed on the basis of the valid standard servicescatalog {{priceCatalogFrom}}."}'
        UNION ALL SELECT N'confirmationOfWorkLabel2',N'{"de":"Dieses Dokument wurde elektronisch erstellt und bedarf keiner Unterschrift des Auftraggebers. Reklamationen/Einsprüche sind innerhalb von 10 Werktagen anzuzeigen.","en":"This document has been produced electronically and requires no signature. Complaints / objections must be reported within q0 working days."}'
        UNION ALL SELECT N'contractingDate',N'{"de":"Ausführungsdatum","en":"ExecutionDate"}'
		UNION ALL SELECT N'customMeasurement',N'{"de":"manuelle Aufmasse","en":"custom Measurement"}'
        UNION ALL SELECT N'dayUnits',N'{"de":"Menge pro Tag","en":"Units per Day"}'
		UNION ALL SELECT N'duplicateMeasurement',N'{"de":"doppelte Aufmasse","en":"duplicate Measurement"}'
        UNION ALL SELECT N'elevation',N'{"de":"Ebene","en":"Elevation"}'
        UNION ALL SELECT N'execution',N'{"de":"Ausführung","en":"Execution"}'
        UNION ALL SELECT N'fileName',N'{"de":"Dateiname","en":"FileName"}'
        UNION ALL SELECT N'floor',N'{"de":"Geschoss","en":"Floor"}'
        UNION ALL SELECT N'increaseReduction',N'{"de":"Erhöhung/Abzug","en":"Increase/Reduction"}'
        UNION ALL SELECT N'lessCIPOf',N'{"de":"abzügl. KVP ","en":"less CIP of "}'
        UNION ALL SELECT N'lessContractionalPenaltyOf',N'{"de":"abzügl. Vertragsstrafe von ","en":"less contractional Penalty of "}'
        UNION ALL SELECT N'lessDayReduction',N'{"de":"abzügl. Tagesabzug","en":"Day Reduction"}'
        UNION ALL SELECT N'lessDiscountOf',N'{"de":"abzügl. Rabatt in Höhe von ","en":"less Discount of "}'
        UNION ALL SELECT N'mainCode',N'{"de":"Hauptcode","en":"MainCode"}'
        UNION ALL SELECT N'mainPosition',N'{"de":"Hauptposition","en":"MainPosition"}'
        UNION ALL SELECT N'mainPositionNumber',N'{"de":"Hauptpositionsnummer","en":"MainPositionNumber"}'
        UNION ALL SELECT N'measurement',N'{"de":"Aufmass","en":"Measurement"}'
        UNION ALL SELECT N'no',N'{"de":"Nein","en":"No"}'
        UNION ALL SELECT N'ownerName',N'{"de":"Bearbeiter","en":"Owner"}'
        UNION ALL SELECT N'page',N'{"de":"Seite","en":"Page"}'
        UNION ALL SELECT N'plant',N'{"de":"Werk","en":"Plant"}'
        UNION ALL SELECT N'pmNumber',N'{"de":"PM-Auftrags-Nr.","en":"PM Number"}'
        UNION ALL SELECT N'positions',N'{"de":"Position(en)","en":"Position(s)"}'
        UNION ALL SELECT N'price',N'{"de":"Preis","en":"Price"}'
        UNION ALL SELECT N'pricePerMonth',N'{"de":"Preis pro Monat","en":"Price per Month"}'
        UNION ALL SELECT N'pricePerYear',N'{"de":"Preis pro Jahr","en":"Price per Year"}'
        UNION ALL SELECT N'quantity',N'{"de":"Menge","en":"Quantity"}'
        UNION ALL SELECT N'rapportNumber',N'{"de":"Rapport-Nr.","en":"Supplier-Ref.No"}'
        UNION ALL SELECT N'realyUnits',N'{"de":"tatsächliche Menge","en":"realy Units"}'
        UNION ALL SELECT N'releaseDate',N'{"de":"Freigabedatum","en":"ReleaseDate"}'
        UNION ALL SELECT N'room',N'{"de":"Raum","en":"Room"}'
        UNION ALL SELECT N'sapOrderNumber',N'{"de":"Bestell-Nr.","en":"SAP OrderNumber"}'
        UNION ALL SELECT N'serviceDate',N'{"de":"Leistungdatum","en":"ServiceDate"}'
        UNION ALL SELECT N'serviceCatalog',N'{"de":"Leistungskatalog","en":"ServiceCatalog"}'
        UNION ALL SELECT N'serviceConfirmation',N'{"de":"Leistungsbescheinigung","en":"ServiceConfirmation"}'
        UNION ALL SELECT N'serviceConfirmationLabel1',N'{"de":"Dieses Dokument wurde elektronisch erstellt und bedarf keiner Unterschrift des Auftraggebers. Reklamationen/Einsprüche sind innerhalb von 10 Werktagen anzuzeigen.","en":"This document has been produced electronically and requires no signature. Complaints / objections must be reported within q0 working days."}'
        UNION ALL SELECT N'serviceConfirmationLabel2',N'{"de":"(2) Preis pro Monat: Eur/ME x Menge/Werktag x 20,83 Werktage/Monat + Eur/ME x Menge/Samstag x 4,25 Samstage/Monat","en":"(1) Price per month: price per unit x units per day x 20,83 working days per month + price per unit x units per day x 4,25 saturdays per month"}'
        UNION ALL SELECT N'serviceOrder',N'{"de":"Leistungsabruf","en":"ServiceOrder"}'
        UNION ALL SELECT N'servicePeriod',N'{"de":"Leistungszeitraum","en":"ServicePeriod"}'
        UNION ALL SELECT N'servicePositionCode',N'{"de":"Position","en":"Position"}'
        UNION ALL SELECT N'servicePositionName',N'{"de":"Leistungsbeschreibung","en":"Service Description"}'
        UNION ALL SELECT N'servicePositionTurnus',N'{"de":"Turnus","en":"Turnus"}'
        UNION ALL SELECT N'servicePositionUnit',N'{"de":"Menge","en":"Unit"}'
        UNION ALL SELECT N'shapeId',N'{"de":"Shape-ID","en":"Shape-ID"}'
        UNION ALL SELECT N'signDateAG',N'{"de":"Datum und Unterschrift AG","en":"Sign and Date Owner"}'
        UNION ALL SELECT N'signDateAN',N'{"de":"Datum und Unterschrift Dienstleister","en":"Sign and Date Supplier"}'
        UNION ALL SELECT N'siteCatalog',N'{"de":"Standortkatalog","en":"SiteCatalog"}'
        UNION ALL SELECT N'standard',N'{"de":"Reinigungsstandard","en":"Standard"}'
        UNION ALL SELECT N'subTotal',N'{"de":"Zwischensumme","en":"Subtotal"}'
        UNION ALL SELECT N'subbuilding',N'{"de":"Gebäudeteil","en":"SubBuilding"}'
        UNION ALL SELECT N'subplant',N'{"de":"Werksteil","en":"SubPlant"}'
        UNION ALL SELECT N'supplierCode',N'{"de":"Lieferanten-Nr.","en":"SupplierNumber"}'
        UNION ALL SELECT N'supplierName',N'{"de":"Auftragnehmer","en":"Supplier"}'
        UNION ALL SELECT N'total',N'{"de":"Summe","en":"Total"}'
        UNION ALL SELECT N'totalMonth',N'{"de":"Summe pro Monat","en":"Total of month"}'
        UNION ALL SELECT N'totalYear',N'{"de":"Summe pro Jahr","en":"Total of year"}'
        UNION ALL SELECT N'totalBillingAmount',N'{"de":"Gesamtsumme","en":"Total BillingAmount"}'
        UNION ALL SELECT N'totalPrice',N'{"de":"Gesamtpreis","en":"TotalPrice"}'
        UNION ALL SELECT N'turnus',N'{"de":"Turnus","en":"Turnus"}'
        UNION ALL SELECT N'unit',N'{"de":"Einheit","en":"Unit"}'
        UNION ALL SELECT N'unitsPerDay',N'{"de":"Tagesmenge","en":"Units per day"}'
        UNION ALL SELECT N'unitPrice',N'{"de":"ME-Preis","en":"UnitPrice"}'
        UNION ALL SELECT N'usageType',N'{"de":"Nutzungsart","en":"Usagetype"}'
        UNION ALL SELECT N'validFrom',N'{"de":"gültig ab","en":"valid from"}'
		UNION ALL SELECT N'updatedAt',N'{"de":"geändert am","en":"changed at"}'
        UNION ALL SELECT N'workOrder',N'{"de":"Auftrag für Rapportarbeiten","en":"WorkOrder"}'        
        UNION ALL SELECT N'workOrderDescription',N'{"de":"Leistungsbeschreibung","en":"Service Description"}'
        UNION ALL SELECT N'workOrderDetails',N'{"de":"Auftrag mit Details","en":"WorkOrder with details"}'       
        UNION ALL SELECT N'workOrderItems',N'{"de":"Auftragspositionen","en":"Work order items"}'
        UNION ALL SELECT N'workOrderLabel1',N'{"de":"Der Auftrag wird gemäß des gültigen Einheispreiskataloges vom {{priceCatalogFrom}} erteilt.","en":"This work order is placed on the basis of the valid standard servicescatalog from {{priceCatalogFrom}}."}'
        UNION ALL SELECT N'workOrderName',N'{"de":"Auftrag","en":"WorkOrder"}'
        UNION ALL SELECT N'workOrderPrices',N'{"de":"Preisblatt","en":"Prices"}' 
        UNION ALL SELECT N'workOrderPricesLabel1',N'{"de":"Der m²-Preis pro Tag ist objektbezogen auf 2 Dezimalstellen anzugeben.","en":"Prices has to be entered with two decimal places"}'
        UNION ALL SELECT N'workOrderPricesLabel2',N'{"de":"(1) tatsächliche Menge: real vorhandene Menge; Tages-Menge: durch Turnusfaktor auf Werktag umgelegte Menge","en":"(1) Actual quantity: quantity actually available; daily quantity: quantity converted to working day by rotation factor"}'
        UNION ALL SELECT N'workOrderPricesLabel3',N'{"de":"(2) Preis pro Monat: Eur/ME x Menge/Werktag x 20,83 Werktage/Monat + Eur/ME x Menge/Samstag x 4,25 Samstage/Monat","en":"(2) Price per month: Eur/ME x quantity/working day x 20.83 working days/month + Eur/ME x quantity/Saturday x 4.25 Saturdays/month"}'
        UNION ALL SELECT N'yes',N'{"de":"Ja","en":"Yes"}'
    ) s
    ON t.[text] = s.[text]
    WHEN NOT MATCHED THEN 
        INSERT([text],[translatedText])
        VALUES(s.[text],s.[translatedText])
    WHEN MATCHED THEN
        UPDATE SET t.[translatedText] = s.[translatedText];


END --reportText
GO


